    spring.application.name=demo
    server.port=${PORT:8080}

    #DataBase Configuration
    spring.datasource.url=${DB_URL}
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

    # JPA Configuration
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    # JWT Configuration
    app.jwt.secret=${JWT_SECRET:change-this-secret-key-to-a-long-random-value-123456}

    # Frontend Configuration
    app.frontend.redirect-url=${FRONTEND_URL:http://localhost:5173}

    # Google OAuth2 Configuration
    spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
    spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
    spring.security.oauth2.client.registration.google.scope=email,profile
    spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
